---
- hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: install docker and git
    yum:
        name: "{{item}}"
        state: present
    loop:
        - git
        - docker
  - name: start docker in host server
    service: name=docker state=started
  - name: to clone the git repo
    git: repo=https://github.com/ragigeo/DevOpsCodeDemo.git dest=/tmp/getrepo
  - name: build the docker file
    command: chdir=/tmp/getrepo docker build -t myansibleimage .
  - name: run thge image and launch the container
    command: docker restart  myansibleimage
    
  
